### PR TITLE
Updating to Swift 5.

### PR DESCRIPTION
**Pull request by tmgsca**
No source code changes. Just project settings update as recommended by the XC converter. All tests are passing.

### CODE REVIEW

**Comment by lilyball** [comment]
I've been a bit leery to do this because Carthage has no way to support multiple swift versions and so I feel like making a change like this requires a major version bump. I may just be overly cautious though.

**Comment by tmgsca** [comment]
Maybe. Would you consider bumping the version then? Right now I have a third-party framework that uses your's as a dependency and I'd love to remove conversion warnings from my project 😅

**Comment by lilyball** [comment]
I really wish CocoaPods could mark up its generated pbxproj files to suppress those warnings.

In any case I'll revisit this soon. I just had a baby so I'm low on time at the moment. I want to make sure I'm comfortable with the versioning strategy when I do this (whether I decide to bump the major version or just declare that Swift version changes a sufficient time after Xcode has been updated are safe).

**Comment by tmgsca** [comment]
Congratz on the baby :). Take your time!

**Pull request closed without merging**
